<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>io.github.luversof</groupId>
	<artifactId>bluesky-boot-devcheck-dependencies</artifactId>
	<version>3.5.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.5</version>
		<relativePath/>
	</parent>
	<properties>
		<java.version>21</java.version>
		<bluesky-boot-devcheck.version>3.5.0-SNAPSHOT</bluesky-boot-devcheck.version>
		
		<!-- (s) central -->
		<central-publishing-maven-plugin.version>0.8.0</central-publishing-maven-plugin.version>
		<maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
		<!-- (e) central -->
	</properties>
	<dependencyManagement>
		<dependencies>
			<!-- (s) bluesky boot devcheck -->
			<dependency>
				<groupId>io.github.luversof</groupId>
				<artifactId>bluesky-boot-devcheck</artifactId>
				<version>${bluesky-boot-devcheck.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.luversof</groupId>
				<artifactId>bluesky-boot-autoconfigure-devcheck</artifactId>
				<version>${bluesky-boot-devcheck.version}</version>
			</dependency>
			<!-- (e) bluesky boot devcheck-->
		</dependencies>
	</dependencyManagement>

	<profiles>
		<profile>
			<id>local</id>
		</profile>
		<profile>
			<id>nexus-k8s</id>
			<repositories>
				<repository>
					<id>bluesky-nexus-k8s</id>
					<url>http://nexus-service:8082/repository/maven-public/</url>
					<releases>
						<enabled>true</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
						<updatePolicy>always</updatePolicy>
					</snapshots>
				</repository>
			</repositories>
			<distributionManagement>
				<repository>
					<id>bluesky-releases</id>
					<url>http://nexus-service:8082/repository/maven-releases/</url>
				</repository>
				<snapshotRepository>
					<id>bluesky-snapshots</id>
					<url>http://nexus-service:8082/repository/maven-snapshots/</url>
				</snapshotRepository>
			</distributionManagement>
		</profile>
		<profile>
			<id>central</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<executions>
							<execution>
								<id>attach-sources</id>
								<goals>
									<goal>jar-no-fork</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<executions>
							<execution>
								<id>attach-javadocs</id>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>${maven-gpg-plugin.version}</version>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.sonatype.central</groupId>
						<artifactId>central-publishing-maven-plugin</artifactId>
						<version>${central-publishing-maven-plugin.version}</version>
						<extensions>true</extensions>
						<configuration>
							<publishingServerId>central</publishingServerId>
							<autoPublish>true</autoPublish>
							<waitUntil>published</waitUntil>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-plugin-plugin</artifactId>
				<version>${maven-plugin-plugin.version}</version>
			</plugin>
		</plugins>
	</reporting>

	<repositories>
		<repository>
			<name>Central Portal Snapshots</name>
			<id>central-portal-snapshots</id>
			<url>https://central.sonatype.com/repository/maven-snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
</project>