<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>bluesky-boot-devcheck-build</artifactId>
	<packaging>pom</packaging>
	<parent>
		<groupId>io.github.luversof</groupId>
		<artifactId>bluesky-boot-devcheck-dependencies</artifactId>
		<version>4.0.0-SNAPSHOT</version>
		<relativePath>./bluesky-boot-devcheck-dependencies</relativePath>
	</parent>
	<name>${project.groupId}:${project.artifactId}</name>
	<description>It is a library that lists and shows the methods of the controller and the utility static methods used for development confirmation.</description>
	<url>https://github.com/luversof/bluesky-boot-devcheck</url>

	<modules>
		<module>bluesky-boot-devcheck-parent</module>
		<module>bluesky-boot-devcheck</module>
		<module>bluesky-boot-devcheck-dependencies</module>
		<module>bluesky-boot-autoconfigure-devcheck</module>
	</modules>

	<inceptionYear>2021</inceptionYear>
	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<connection>scm:git:git://github.com/luversof/bluesky-boot-devcheck.git</connection>
		<developerConnection>scm:git:ssh://github.com:luversof/bluesky-boot-devcheck.git</developerConnection>
		<url>http://github.com/luversof/bluesky-boot-devcheck/tree/main</url>
	</scm>

	<developers>
		<developer>
			<name>luversof</name>
			<email>luversof@hanmail.net</email>
		</developer>
	</developers>


</project>