<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.luversof</groupId>
		<artifactId>bluesky-boot-devcheck-parent</artifactId>
		<version>4.0.0-SNAPSHOT</version>
		<relativePath>../bluesky-boot-devcheck-parent</relativePath>
	</parent>
	<artifactId>bluesky-boot-autoconfigure-devcheck</artifactId>
	<dependencies>
		<dependency>
			<groupId>io.github.luversof</groupId>
			<artifactId>bluesky-boot-devcheck</artifactId>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<optional>true</optional>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aspectj</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- (s) test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- (e) test -->

		<!-- (s) servlet web -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-core</artifactId>
			<optional>true</optional>
		</dependency>
		<!-- (e) servlet web -->

		<!-- (s) webflux -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
			<optional>true</optional>
		</dependency>
		<!-- (e) webflux -->

	</dependencies>
</project>